yatube/posts/urls.py
from django.urls.resolvers import URLPattern
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),  # Главная страница
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),  # Страницы постов по группам
] 

yatube/yatube/urls.py
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path

from django.conf import settings

urlpatterns = [
    path('', include('posts.urls', namespace='posts')), # импорт правил из приложения posts
    path('admin/', admin.site.urls),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:  # Если DEBUG=True в настройках
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Раздаем статичные файлы с сервера разработки runserver
    urlpatterns += staticfiles_urlpatterns()

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )
        
    def __str__(self, title):
        self.title: str = title

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse

from .models import Group, Post

# Create your views here.
def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 

# в URL мы ждем параметр и его нужно передать в функцию для
def group_posts(request, slug):
    # Функция get_object_or_494 получает по заданным критериям объект
    # из бызы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">          
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" type="image" img src="{% static 'img/fav/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" img src="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" img src="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" img src="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Последние обновления на сайте</title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <title>{% block title %}{% endblock %}</title>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube</a>
        </a>
      </div>
    </nav>      
  </header>

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Лев Толстой – зеркало русской революции.</h1>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          {% for post in posts %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>
              {{ post.text }}
            </p>
          {% endfor %}         
        </article>
        <hr>                
        <!-- под последним постом нет линии -->
      </div>  
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
       <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Последние обновления на сайте</h1>
        <article>
          {% for post in posts %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>{{ post.text }}</p>
            {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}         
        </article>
        <!-- под последним постом нет линии -->
      </div>      
{% endblock %}